services:
  postgres:
    container_name: postgres_messenger
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - messenger
    ports:
      - "5436:5432"
    restart: unless-stopped
networks:
  messenger:
    driver: bridge
volumes:
  postgres_volume: