services:
  postgres:
    container_name: postgres_messenger
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    networks:
      - messenger
    ports:
      - "5436:5432"
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_messenger
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - messenger
    restart: unless-stopped


networks:
  messenger:
    driver: bridge
volumes:
  postgres_volume:
  pgadmin: